import smbl
import mishmash

fe=smbl.fasta.EXAMPLE

# problem -- lomitko na konci
mishmash.ArtIllumina(fa=fe,coverage=1,read_length_1=100,read_length_2=0)
mishmash.DwgSim(fa=fe,coverage=1)
mishmash.DwgSim(fa=fe,read_length_1=100,read_length_2=100,coverage=1)

include: mishmash.include

rule basic:
	input:
		mishmash.output
