import smbl
import mishmash

fasta=smbl.fasta.HUMAN_HG38
#fasta=smbl.fasta.EXAMPLE

#
# SINGLE-END
#
mishmash.sample("single_end_example")

mishmash.ArtIllumina(
	fa=fasta,
	number_of_reads=10000,
	read_length_1=100,
	read_length_2=0,
)

mishmash.DwgSim(
	fa=fasta,
	number_of_reads=10000,
	read_length_1=100,
	read_length_2=0,
)


#
# PAIR-END
#

mishmash.sample("pair_end_example")


mishmash.ArtIllumina(
	fa=fasta,
	number_of_reads=10000,
	read_length_1=100,
	read_length_2=100,
)

mishmash.DwgSim(
	fa=fasta,
	number_of_reads=10000,
	read_length_1=100,
	read_length_2=100,
)

include: mishmash.include
rule: input: mishmash.input
		
