import smbl
import rnftools


fasta=smbl.fasta.HUMAN_HG38
fasta=smbl.fasta.EXAMPLE

test_art_illumina   = True
test_wgsim          = True
test_dwgsim         = True
test_curesim        = True

#test_art_illumina   = False
#test_wgsim          = False
#test_dwgsim         = False
#test_curesim        = False


#
# SINGLE-END
#
rnftools.mishmash.sample("single_end_example",reads_in_tuple=1)

if test_art_illumina:
	rnftools.mishmash.ArtIllumina(
		fasta=fasta,
		number_of_read_tuples=10000,
		read_length_1=100,
		read_length_2=0,
	)

if test_dwgsim:
	rnftools.mishmash.DwgSim(
		fasta=fasta,
		number_of_read_tuples=10000,
		read_length_1=100,
		read_length_2=0,
	)

if test_wgsim:
	rnftools.mishmash.WgSim(
		fasta=fasta,
		number_of_read_tuples=10000,
		read_length_1=100,
		read_length_2=0,
	)

if test_curesim:
	rnftools.mishmash.CuReSim(
		fasta=fasta,
		number_of_read_tuples=10000,
		read_length_1=100,
		read_length_2=0,
	)


#
# PAIR-END
#

rnftools.mishmash.sample("pair_end_example",reads_in_tuple=2)

if test_art_illumina:
	rnftools.mishmash.ArtIllumina(
		fasta=fasta,
		number_of_read_tuples=10000,
		read_length_1=100,
		read_length_2=100,
	)

if test_dwgsim:
	rnftools.mishmash.DwgSim(
		fasta=fasta,
		number_of_read_tuples=10000,
		read_length_1=100,
		read_length_2=100,
	)

if test_wgsim:
	rnftools.mishmash.WgSim(
		fasta=fasta,
		number_of_read_tuples=10000,
		read_length_1=100,
		read_length_2=100,
	)


include: rnftools.include()
rule: input: rnftools.input()
