import rnftools

rnftools.mishmash.sample("simple_example",reads_in_tuple=1)

fa1="../../../example1.fa"
fa2="../../../example2.fa"

rnftools.mishmash.ArtIllumina(
	fasta=fa1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.ArtIllumina(
	fasta=fa2,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
)

include: rnftools.include()
rule: input: rnftools.input()
