import rnftools
import smbl

rnftools.mishmash.sample("simple_example",reads_in_tuple=1)

rnftools.mishmash.ArtIllumina(
	fasta=smbl.fasta.EXAMPLE_1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
	other_params="-qs 5",
)

include: rnftools.include()
rule: input: rnftools.input()
