import rnftools

rnftools.mishmash.sample("test_se",reads_in_tuple=1)

fa="../../hiv.fa"

rnftools.mishmash.ArtIllumina(
	fasta=fa,
	number_of_read_tuples=0,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.CuReSim(
	fasta=fa,
	number_of_read_tuples=0,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.DwgSim(
	fasta=fa,
	number_of_read_tuples=0,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.MasonIllumina(
	fasta=fa,
	number_of_read_tuples=0,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.WgSim(
	fasta=fa,
	number_of_read_tuples=0,
	read_length_1=100,
	read_length_2=0,
)

include: rnftools.include()
rule: input: rnftools.input()
