import rnftools

rnftools.mishmash.sample("reads_first_sequence",reads_in_tuple=1)

rnftools.mishmash.ArtIllumina(
	fasta="example.fa",
	sequences=[0],
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.sample("reads_second_sequence",reads_in_tuple=1)

rnftools.mishmash.ArtIllumina(
	fasta="example.fa",
	sequences=['seq2'],
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
)


include: rnftools.include()
rule: input: rnftools.input()
