import rnftools
import smbl

rnftools.mishmash.sample("se_example",reads_in_tuple=1)

rnftools.mishmash.ArtIllumina(
	fasta=smbl.fasta.EXAMPLE_1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.MasonIllumina(
	fasta=smbl.fasta.EXAMPLE_1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.DwgSim(
	fasta=smbl.fasta.EXAMPLE_1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.WgSim(
	fasta=smbl.fasta.EXAMPLE_1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
)

rnftools.mishmash.CuReSim(
	fasta=smbl.fasta.EXAMPLE_1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=0,
)


rnftools.mishmash.sample("pe_example",reads_in_tuple=2)

rnftools.mishmash.ArtIllumina(
	fasta=smbl.fasta.EXAMPLE_1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=100,
)

rnftools.mishmash.MasonIllumina(
	fasta=smbl.fasta.EXAMPLE_1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=100,
)

rnftools.mishmash.DwgSim(
	fasta=smbl.fasta.EXAMPLE_1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=100,
)

rnftools.mishmash.WgSim(
	fasta=smbl.fasta.EXAMPLE_1,
	number_of_read_tuples=10000,
	read_length_1=100,
	read_length_2=100,
)

include: rnftools.include()
rule: input: rnftools.input()
