import rnftools


a=rnftools.lavender.Report(
	name="experiment",
	panels=[
		{
			"panel_dir": "experiment_1",
			"bam_dir": "../bams",
			"title": "Title 1",
		},
		{
			"panel_dir": "experiment_2",
			"bam_dir": "../bams",
			"title": "Title 2",
		},
	],
	default_y_run=(0,100),
	#default_x_run=(0.0001,1.0),
	default_x_run=(0.005,.5),
	keep_intermediate_files=True,
)

rule all: input: rnftools.input()

include: rnftools.include()

