import rnftools

rnftools.mishmash.sample("test_pe",reads_in_tuple=2)

fa="../../hiv.fa"

rnftools.mishmash.ArtIllumina(
	fasta=fa,
	number_of_read_tuples=0,
	read_length_1=100,
	read_length_2=100,
)

rnftools.mishmash.DwgSim(
	fasta=fa,
	number_of_read_tuples=0,
	read_length_1=100,
	read_length_2=150,
)

rnftools.mishmash.MasonIllumina(
	fasta=fa,
	number_of_read_tuples=0,
	read_length_1=100,
	read_length_2=100,
)

rnftools.mishmash.WgSim(
	fasta=fa,
	number_of_read_tuples=0,
	read_length_1=100,
	read_length_2=150,
)

include: rnftools.include()
rule: input: rnftools.input()
