import rnftools
import smbl

rnftools.mishmash.sample("test_metagenomic_pe",reads_in_tuple=2)

for i in range(1000):
	rnftools.mishmash.DwgSim(
		fasta="../NC_014663_reduced.fna",
		number_of_read_tuples=1,
		read_length_1=30,
		read_length_2=30,
	)


include: rnftools.include()
rule: input: rnftools.input()
