import rnftools

rnftools.mishmash.sample("test_metagenomic_se",reads_in_tuple=1)

fa="../../hiv.fa"

for i in range(500):
	rnftools.mishmash.DwgSim(
		fasta="../NC_014663_reduced.fna",
		number_of_read_tuples=1,
		read_length_1=30,
		read_length_2=0,
	)


include: rnftools.include()
rule: input: rnftools.input()
