import smbl
from rnftools import mishmash

fasta=smbl.fasta.EXAMPLE

mishmash.sample("simple_example",ends=1)

mishmash.ArtIllumina(
	fa=fasta,
	number_of_reads=10000,
	read_length_1=100,
	read_length_2=0,
)

include: mishmash.include()
rule: input: mishmash.input()
