import smbl
import rnftools

fasta=smbl.fasta.EXAMPLE

rnftools.mishmash.sample("simple_example",ends=1)

rnftools.mishmash.ArtIllumina(
	fa=fasta,
	number_of_reads=10000,
	read_length_1=100,
	read_length_2=0,
)

include: rnftools.include()
rule: input: rnftools.input()
